FORMAT: 1A
HOST: http://rooms.dhappy.org/

# Reservations

An API for managing hostel reservations.

## Rooms [/rooms]

+ Attributes (array)
    - (object)
        - name: 100
        - number: 1 (number)

### List [GET]

+ Response 200 (application/json)

    + Attributes
        - rooms (Rooms)

## Room [/rooms/{id}]

+ Attributes
    - name: 703A
    - beds
      - 1 (number) - id of a bed
      - 2 (number)
      - 3 (number)
    - gender (enum)
        - male
        - female
        - mixed
    - amenities (array)
        - (object)
            - name: sink
        - (object)
            - name: toilet

### List [GET]

+ Response 200 (application/json)

    + Attributes
        - rooms (array)
            - (Rooms)

## Beds [/beds]

+ Attributes
    - number: 1 (number)
    - room: 0 (number) - id of containing room
    - dirty: true (boolean)
    - reservations 
      - 1 (number)
      - 2 (number)
      - 3 (number)
   
### List [GET]

+ Response 200 (application/json)

## Clients [/clients]

+ Attributes
    - name: Joe Client - printable name
    - email: Joe@g.co
    - addresses
      - 1 (number)
      - 2 (number)
      - 3 (number)
    - reservations 
      - 1 (number)
      - 2 (number)
      - 3 (number)
   
### List [GET]

+ Response 200 (application/json)


## Reservations [/reservations]

+ Attributes
    - name: First Floor - printable name
    
### List [GET]

+ Response 200 (application/json)